version: "3.8"

services:
  # 1. Service Database (MySQL)
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: node_blog_db
      MYSQL_ROOT_PASSWORD: "123456"
    ports:
      - "3307:3306" # Đổi chỗ này sếp nhé
    volumes:
      - db_data:/var/lib/mysql

  # 2. Service App (Node.js)
  app:
    build: .
    ports:
      - "8081:8080" # Khớp với PORT=8080 trong .env của sếp
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=node_blog_db
      - DB_PORT=3306
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  db_data:
